services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/certs:/certs:ro
      - /opt/traefik/dynamic:/dynamic:ro
    command:
      # EntryPoints
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - --providers.file.filename=/dynamic/tls.yaml
      # Providers 
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      # API & Dashboard 
      - --api.dashboard=true
      - --api.insecure=false
      # Observability 
      - --log.level=INFO
      - --accesslog=true
      - --metrics.prometheus=false
    # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - traefik.enable=true
      # Dashboard router
      - traefik.http.routers.dashboard.rule=Host(`traefik.lab.son`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls=true

networks:
  proxy:
    name: proxy
