services:
  glance:
    container_name: glance
    deploy:
      resources:
        limits:
          memory: 1024M
    image: glanceapp/glance:latest
    ports:
      - 8088:8080
    restart: unless-stopped
    volumes:
      - /opt/stacks/glance/config/:/app/config/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.glance.rule=Host(`glance.lab.son`) || Host(`lab.son`)
      - traefik.http.routers.glance.entrypoints=websecure
      - traefik.http.routers.glance.tls=true
networks:
  proxy:
    external: true
